name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"

    #   - name: Install dependencies
    #     run: |
    #         python -m pip install --upgrade pip
    #         pip install torch --index-url https://download.pytorch.org/whl/cpu
    #         pip install -r requirements.txt

      - name: Syntax Check
        run: |
            python -m compileall app

      - name: Build RAG API Docker image
        run: |
            docker build -t devdocs-rag-api .
